receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

exporters:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
  otlp:
    endpoint: "localhost:14250"
    tls:
      insecure: true
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, debug]
      processors: [batch]

processors:
  batch: